#!/bin/bash

#
# Credits:
# http://www.placona.co.uk
#

# debug
set -x

# variables
dotfiles_dir="~/dotfiles"            # dotfiles directory
dotfiles_olddir="~/dotfiles_old"     # old dotfiles backup directory

# list of files/folders to symlink in homedir
files=".bashrc .vimrc .vim"

# create dotfiles_old in homedir
mkdir -p $dotfiles_olddir

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks 
for file in $files; do
    echo "Moving any existing dotfiles from ~ to $dotfiles_olddir"
    mv ~/$file ~/${dotfiles_olddir}/
    echo "Creating symlink to $file in home directory."
    ln -s $dotfiles_dir/$file ~/$file
done

# source the bashrc file
. ~/.bashrc
