#!/bin/bash

#
# Credits:
# Parts of this script was inspired by the one found at:
# http://www.placona.co.uk
#

# debug
#set -x

# list of files/folders to symlink in homedir, remove an item if you dont wanna install all of them
files="bashrc vimrc vim Xresources i3"


# variables
dotfiles_dir="dotfiles"            # dotfiles directory
dotfiles_olddir="dotfiles_old"     # old dotfiles backup directory

# wanna proceed?
printf "%s\n" "The following configuration files/dirs will be moved to $dotfiles_olddir:"
printf "%s\n" "$files"
printf "\n%s" "Continue? [s/n]: "
read answer

if [ $answer != "s" ] ; then
    printf "%s\n" "aborted."
    exit 1
fi

# cd to home dir
cd ~
# create dir for the current files
mkdir -p $dotfiles_olddir
# create tmp dir for vim config
mkdir -p .vim/tmp

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks 
for file in $files; do
    echo "Moving any existing dotfiles from ~ to $dotfiles_olddir"
    mv .$file ${dotfiles_olddir}/
    echo "Creating symlink to $file in home directory."
    ln -s $dotfiles_dir/$file .$file
done

# source the bashrc file
. ~/.bashrc

# download vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# reminder..
printf "\n%s\n" "Launch vim and run :PluginInstall"

exit 0
